default_platform(:ios)

platform :ios do
  desc "Build beta iOS artifact"
  lane :beta_ios do
    sh("flutter pub get")
    sh("flutter build ipa --release --no-codesign")
  end

  desc "Release iOS artifact"
  lane :release_ios do
    sh("flutter pub get")
    sh("flutter build ipa --release")
  end
end

